///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AddCartModelCart {
/*
{
  "key": "29ddbdb402491a6aa97964a8139a1356",
  "product_id": "3382"
}
*/

  String? key;
  String? productId;

  AddCartModelCart({
    this.key,
    this.productId,
  });
  AddCartModelCart.fromJson(Map<String, dynamic> json) {
    key = json['key']?.toString();
    productId = json['product_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['key'] = key;
    data['product_id'] = productId;
    return data;
  }
}

class AddCartModel {
/*
{
  "cart": [
    {
      "key": "29ddbdb402491a6aa97964a8139a1356",
      "product_id": "3382"
    }
  ],
  "total": 50,
  "sub_total": 50,
  "status": true
}
*/

  List<AddCartModelCart?>? cart;
  int? total;
  int? subTotal;
  bool? status;

  AddCartModel({
    this.cart,
    this.total,
    this.subTotal,
    this.status,
  });
  AddCartModel.fromJson(Map<String, dynamic> json) {
    if (json['cart'] != null) {
      final v = json['cart'];
      final arr0 = <AddCartModelCart>[];
      v.forEach((v) {
        arr0.add(AddCartModelCart.fromJson(v));
      });
      cart = arr0;
    }
    total = json['total']?.toInt();
    subTotal = json['sub_total']?.toInt();
    status = json['status'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (cart != null) {
      final v = cart;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['cart'] = arr0;
    }
    data['total'] = total;
    data['sub_total'] = subTotal;
    data['status'] = status;
    return data;
  }
}
