///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AddressSuccessModel {
/*
{
  "success": true,
  "msg": "Shipping address added successfully!"
}
*/

  bool? success;
  String? msg;

  AddressSuccessModel({
    this.success,
    this.msg,
  });
  AddressSuccessModel.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    msg = json["msg"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    data["msg"] = msg;
    return data;
  }
}
