///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AddressListModelData {
/*
{
  "key": "617104f2192ec",
  "first_name": "Suraj",
  "last_name": "Patel",
  "address": "Karnavati",
  "city": "Surat",
  "state": "Gujarat",
  "postcode": "565659",
  "country": "India"
}
*/

  String? key;
  String? firstName;
  String? lastName;
  String? address;
  String? city;
  String? state;
  String? postcode;
  String? country;

  AddressListModelData({
    this.key,
    this.firstName,
    this.lastName,
    this.address,
    this.city,
    this.state,
    this.postcode,
    this.country,
  });
  AddressListModelData.fromJson(Map<String, dynamic> json) {
    key = json["key"]?.toString();
    firstName = json["first_name"]?.toString();
    lastName = json["last_name"]?.toString();
    address = json["address"]?.toString();
    city = json["city"]?.toString();
    state = json["state"]?.toString();
    postcode = json["postcode"]?.toString();
    country = json["country"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["key"] = key;
    data["first_name"] = firstName;
    data["last_name"] = lastName;
    data["address"] = address;
    data["city"] = city;
    data["state"] = state;
    data["postcode"] = postcode;
    data["country"] = country;
    return data;
  }
}

class AddressListModel {
/*
{
  "success": true,
  "data": [
    {
      "key": "617104f2192ec",
      "first_name": "Suraj",
      "last_name": "Patel",
      "address": "Karnavati",
      "city": "Surat",
      "state": "Gujarat",
      "postcode": "565659",
      "country": "India"
    }
  ]
}
*/

  bool? success;
  List<AddressListModelData?>? data;

  AddressListModel({
    this.success,
    this.data,
  });
  AddressListModel.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    if (json["data"] != null) {
      final v = json["data"];
      final arr0 = <AddressListModelData>[];
      v.forEach((v) {
        arr0.add(AddressListModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["data"] = arr0;
    }
    return data;
  }
}
