///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AddShipModel {
/*
{
  "success": true,
  "shipping_charge": 0,
  "total": 1278
}
*/

  bool? success;
  dynamic? shippingCharge;
  dynamic total;

  AddShipModel({
    this.success,
    this.shippingCharge,
    this.total,
  });
  AddShipModel.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    shippingCharge = json["shipping_charge"];
    total = json["total"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    data["shipping_charge"] = shippingCharge;
    data["total"] = total;
    return data;
  }
}
