///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CategoryModelLinksUp {
/*
{
  "href": "https://encros.rcstaging.co.in/wp-json/wc/v3/products/categories/7280"
}
*/

  String? href;

  CategoryModelLinksUp({
    this.href,
  });
  CategoryModelLinksUp.fromJson(Map<String, dynamic> json) {
    href = json["href"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["href"] = href;
    return data;
  }
}

class CategoryModelLinksCollection {
/*
{
  "href": "https://encros.rcstaging.co.in/wp-json/wc/v3/products/categories"
}
*/

  String? href;

  CategoryModelLinksCollection({
    this.href,
  });
  CategoryModelLinksCollection.fromJson(Map<String, dynamic> json) {
    href = json["href"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["href"] = href;
    return data;
  }
}

class CategoryModelLinksSelf {
/*
{
  "href": "https://encros.rcstaging.co.in/wp-json/wc/v3/products/categories/7281"
}
*/

  String? href;

  CategoryModelLinksSelf({
    this.href,
  });
  CategoryModelLinksSelf.fromJson(Map<String, dynamic> json) {
    href = json["href"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["href"] = href;
    return data;
  }
}

class CategoryModelLinks {
/*
{
  "self": [
    {
      "href": "https://encros.rcstaging.co.in/wp-json/wc/v3/products/categories/7281"
    }
  ],
  "collection": [
    {
      "href": "https://encros.rcstaging.co.in/wp-json/wc/v3/products/categories"
    }
  ],
  "up": [
    {
      "href": "https://encros.rcstaging.co.in/wp-json/wc/v3/products/categories/7280"
    }
  ]
}
*/

  List<CategoryModelLinksSelf?>? self;
  List<CategoryModelLinksCollection?>? collection;
  List<CategoryModelLinksUp?>? up;

  CategoryModelLinks({
    this.self,
    this.collection,
    this.up,
  });
  CategoryModelLinks.fromJson(Map<String, dynamic> json) {
    if (json["self"] != null) {
      final v = json["self"];
      final arr0 = <CategoryModelLinksSelf>[];
      v.forEach((v) {
        arr0.add(CategoryModelLinksSelf.fromJson(v));
      });
      self = arr0;
    }
    if (json["collection"] != null) {
      final v = json["collection"];
      final arr0 = <CategoryModelLinksCollection>[];
      v.forEach((v) {
        arr0.add(CategoryModelLinksCollection.fromJson(v));
      });
      collection = arr0;
    }
    if (json["up"] != null) {
      final v = json["up"];
      final arr0 = <CategoryModelLinksUp>[];
      v.forEach((v) {
        arr0.add(CategoryModelLinksUp.fromJson(v));
      });
      up = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (self != null) {
      final v = self;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["self"] = arr0;
    }
    if (collection != null) {
      final v = collection;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["collection"] = arr0;
    }
    if (up != null) {
      final v = up;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["up"] = arr0;
    }
    return data;
  }
}

class CategoryModel {
/*
{
  "id": 7281,
  "name": " 9017 noir.",
  "slug": "9017-noir",
  "parent": 7280,
  "description": "",
  "display": "default",
  "image": null,
  "menu_order": 0,
  "count": 0,
  "_links": {
    "self": [
      {
        "href": "https://encros.rcstaging.co.in/wp-json/wc/v3/products/categories/7281"
      }
    ],
    "collection": [
      {
        "href": "https://encros.rcstaging.co.in/wp-json/wc/v3/products/categories"
      }
    ],
    "up": [
      {
        "href": "https://encros.rcstaging.co.in/wp-json/wc/v3/products/categories/7280"
      }
    ]
  }
}
*/

  int? id;
  String? name;
  String? slug;
  int? parent;
  String? description;
  String? display;
  String? image;
  int? menuOrder;
  int? count;
  CategoryModelLinks? Links;

  CategoryModel({
    this.id,
    this.name,
    this.slug,
    this.parent,
    this.description,
    this.display,
    this.image,
    this.menuOrder,
    this.count,
    this.Links,
  });
  CategoryModel.fromJson(Map<dynamic, dynamic> json) {
    id = json["id"]?.toInt();
    name = json["name"]?.toString();
    slug = json["slug"]?.toString();
    parent = json["parent"]?.toInt();
    description = json["description"]?.toString();
    display = json["display"]?.toString();
    image = json["image"]?.toString();
    menuOrder = json["menu_order"]?.toInt();
    count = json["count"]?.toInt();
    Links = (json["_links"] != null) ? CategoryModelLinks.fromJson(json["_links"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    data["slug"] = slug;
    data["parent"] = parent;
    data["description"] = description;
    data["display"] = display;
    data["image"] = image;
    data["menu_order"] = menuOrder;
    data["count"] = count;
    if (Links != null) {
      data["_links"] = Links!.toJson();
    }
    return data;
  }
}
