///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CategoryModelCategories {
/*
{
  "id": 191,
  "name": "Appliances"
}
*/

  int? id;
  String? name;

  CategoryModelCategories({
    this.id,
    this.name,
  });
  CategoryModelCategories.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}

class CategoryModel {
/*
{
  "success": true,
  "categories": [
    {
      "id": 191,
      "name": "Appliances"
    }
  ]
}
*/

  bool? success;
  List<CategoryModelCategories?>? categories;

  CategoryModel({
    this.success,
    this.categories,
  });
  CategoryModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['categories'] != null) {
      final v = json['categories'];
      final arr0 = <CategoryModelCategories>[];
      v.forEach((v) {
        arr0.add(CategoryModelCategories.fromJson(v));
      });
      categories = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (categories != null) {
      final v = categories;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['categories'] = arr0;
    }
    return data;
  }
}
