///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CountryParishModelDataCountriesParishes {
/*
{
  "id": "116",
  "name": "Christ Church",
  "country": "Barbados",
  "created_at": null,
  "updated_at": "2020-10-24 14:20:18"
}
*/

  String? id;
  String? name;
  String? country;
  String? createdAt;
  String? updatedAt;

  CountryParishModelDataCountriesParishes({
    this.id,
    this.name,
    this.country,
    this.createdAt,
    this.updatedAt,
  });
  CountryParishModelDataCountriesParishes.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    country = json['country']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['country'] = country;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}

class CountryParishModelDataCountries {
/*
{
  "country": "Barbados",
  "parishes": [
    {
      "id": "116",
      "name": "Christ Church",
      "country": "Barbados",
      "created_at": null,
      "updated_at": "2020-10-24 14:20:18"
    }
  ]
}
*/

  String? country;
  List<CountryParishModelDataCountriesParishes?>? parishes;

  CountryParishModelDataCountries({
    this.country,
    this.parishes,
  });
  CountryParishModelDataCountries.fromJson(Map<String, dynamic> json) {
    country = json['country']?.toString();
    if (json['parishes'] != null) {
      final v = json['parishes'];
      final arr0 = <CountryParishModelDataCountriesParishes>[];
      v.forEach((v) {
        arr0.add(CountryParishModelDataCountriesParishes.fromJson(v));
      });
      parishes = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    if (parishes != null) {
      final v = parishes;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['parishes'] = arr0;
    }
    return data;
  }
}

class CountryParishModelData {
/*
{
  "countries": [
    {
      "country": "Barbados",
      "parishes": [
        {
          "id": "116",
          "name": "Christ Church",
          "country": "Barbados",
          "created_at": null,
          "updated_at": "2020-10-24 14:20:18"
        }
      ]
    }
  ]
}
*/

  List<CountryParishModelDataCountries?>? countries;

  CountryParishModelData({
    this.countries,
  });
  CountryParishModelData.fromJson(Map<String, dynamic> json) {
    if (json['countries'] != null) {
      final v = json['countries'];
      final arr0 = <CountryParishModelDataCountries>[];
      v.forEach((v) {
        arr0.add(CountryParishModelDataCountries.fromJson(v));
      });
      countries = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (countries != null) {
      final v = countries;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['countries'] = arr0;
    }
    return data;
  }
}

class CountryParishModel {
/*
{
  "success": true,
  "data": {
    "countries": [
      {
        "country": "Barbados",
        "parishes": [
          {
            "id": "116",
            "name": "Christ Church",
            "country": "Barbados",
            "created_at": null,
            "updated_at": "2020-10-24 14:20:18"
          }
        ]
      }
    ]
  }
}
*/

  bool? success;
  CountryParishModelData? data;

  CountryParishModel({
    this.success,
    this.data,
  });
  CountryParishModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = (json['data'] != null) ? CountryParishModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
