///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CouponModelCartCouponDiscountTotals {
/*
{
  "coupon_title": "flat50",
  "coupon_price": "0"
}
*/

  String? couponTitle;
  dynamic? couponPrice;

  CouponModelCartCouponDiscountTotals({
    this.couponTitle,
    this.couponPrice,
  });
  CouponModelCartCouponDiscountTotals.fromJson(Map<String, dynamic> json) {
    couponTitle = json["coupon_title"]?.toString();
    couponPrice = json["coupon_price"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["coupon_title"] = couponTitle;
    data["coupon_price"] = couponPrice;
    return data;
  }
}


class CouponModelCartCart {
/*
{
  "key": "d027992c243115078df9628a3dc0bc96",
  "product_id": "85775",
  "variation_id": "",
  "variation": [
    null
  ],
  "quantity": 2,
  "line_subtotal": 28.22,
  "line_total": 28.22,
  "line_tax_data": {
    "subtotal": [
      null
    ],
    "total": [
      null
    ]
  },
  "line_subtotal_tax": 0,
  "line_tax": 0,
  "product_name": "01126301 - Ruban matriciel Oki 01126301 noir pour ML-5500",
  "product_type": "simple",
  "product_price": "14.11000",
  "product_image": "https://encros.rcstaging.co.in/wp-content/uploads/2021/06/MAT039.jpg"
}
*/

  String? key;
  dynamic? productId;
  dynamic? variationId;
  dynamic? quantity;
  dynamic? lineSubtotal;
  dynamic? lineTotal;
  String? productName;
  String? productType;
  String? productPrice;
  String? productImage;

  CouponModelCartCart({
    this.key,
    this.productId,
    this.variationId,
    this.quantity,
    this.lineSubtotal,
    this.lineTotal,
    this.productName,
    this.productType,
    this.productPrice,
    this.productImage,
  });
  CouponModelCartCart.fromJson(Map<String, dynamic> json) {
    key = json["key"]?.toString();
    productId = json["product_id"]?.toString();
    variationId = json["variation_id"]?.toString();
    quantity = json["quantity"];
    lineSubtotal = json["line_subtotal"]?.toDouble();
    lineTotal = json["line_total"]?.toDouble();
    productName = json["product_name"]?.toString();
    productType = json["product_type"]?.toString();
    productPrice = json["product_price"]?.toString();
    productImage = json["product_image"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["key"] = key;
    data["product_id"] = productId;
    data["variation_id"] = variationId;
    data["quantity"] = quantity;
    data["line_subtotal"] = lineSubtotal;
    data["line_total"] = lineTotal;

    data["product_name"] = productName;
    data["product_type"] = productType;
    data["product_price"] = productPrice;
    data["product_image"] = productImage;
    return data;
  }
}

class CouponModelCart {
/*
{
  "cart": [
    {
      "key": "d027992c243115078df9628a3dc0bc96",
      "product_id": "85775",
      "variation_id": "",
      "variation": [
        null
      ],
      "quantity": 2,
      "line_subtotal": 28.22,
      "line_total": 28.22,
      "line_tax_data": {
        "subtotal": [
          null
        ],
        "total": [
          null
        ]
      },
      "line_subtotal_tax": 0,
      "line_tax": 0,
      "product_name": "01126301 - Ruban matriciel Oki 01126301 noir pour ML-5500",
      "product_type": "simple",
      "product_price": "14.11000",
      "product_image": "https://encros.rcstaging.co.in/wp-content/uploads/2021/06/MAT039.jpg"
    }
  ],
  "total": 1278.22,
  "sub_total": 1278.22,
  "applied_coupons": [
    "flat50"
  ],
  "coupon_discount_totals": [
    {
      "coupon_title": "flat50",
      "coupon_price": "0"
    }
  ],
  "status": true
}
*/

  List<CouponModelCartCart?>? cart;
  double? total;
  double? subTotal;
  List<String?>? appliedCoupons;
  List<CouponModelCartCouponDiscountTotals?>? couponDiscountTotals;
  bool? status;

  CouponModelCart({
    this.cart,
    this.total,
    this.subTotal,
    this.appliedCoupons,
    this.couponDiscountTotals,
    this.status,
  });
  CouponModelCart.fromJson(Map<String, dynamic> json) {
    if (json["cart"] != null) {
      final v = json["cart"];
      final arr0 = <CouponModelCartCart>[];
      v.forEach((v) {
        arr0.add(CouponModelCartCart.fromJson(v));
      });
      cart = arr0;
    }
    total = json["total"]?.toDouble();
    subTotal = json["sub_total"]?.toDouble();
    if (json["applied_coupons"] != null) {
      final v = json["applied_coupons"];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      appliedCoupons = arr0;
    }
    if (json["coupon_discount_totals"] != null) {
      final v = json["coupon_discount_totals"];
      final arr0 = <CouponModelCartCouponDiscountTotals>[];
      v.forEach((v) {
        arr0.add(CouponModelCartCouponDiscountTotals.fromJson(v));
      });
      couponDiscountTotals = arr0;
    }
    status = json["status"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (cart != null) {
      final v = cart;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["cart"] = arr0;
    }
    data["total"] = total;
    data["sub_total"] = subTotal;
    if (appliedCoupons != null) {
      final v = appliedCoupons;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data["applied_coupons"] = arr0;
    }
    if (couponDiscountTotals != null) {
      final v = couponDiscountTotals;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["coupon_discount_totals"] = arr0;
    }
    data["status"] = status;
    return data;
  }
}

class CouponModel {
/*
{
  "success": true,
  "cart": {
    "cart": [
      {
        "key": "d027992c243115078df9628a3dc0bc96",
        "product_id": "85775",
        "variation_id": "",
        "variation": [
          null
        ],
        "quantity": 2,
        "line_subtotal": 28.22,
        "line_total": 28.22,
        "line_tax_data": {
          "subtotal": [
            null
          ],
          "total": [
            null
          ]
        },
        "line_subtotal_tax": 0,
        "line_tax": 0,
        "product_name": "01126301 - Ruban matriciel Oki 01126301 noir pour ML-5500",
        "product_type": "simple",
        "product_price": "14.11000",
        "product_image": "https://encros.rcstaging.co.in/wp-content/uploads/2021/06/MAT039.jpg"
      }
    ],
    "total": 1278.22,
    "sub_total": 1278.22,
    "applied_coupons": [
      "flat50"
    ],
    "coupon_discount_totals": [
      {
        "coupon_title": "flat50",
        "coupon_price": "0"
      }
    ],
    "status": true
  }
}
*/

  bool? success;
  CouponModelCart? cart;

  CouponModel({
    this.success,
    this.cart,
  });
  CouponModel.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    cart = (json["cart"] != null) ? CouponModelCart.fromJson(json["cart"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (cart != null) {
      data["cart"] = cart!.toJson();
    }
    return data;
  }
}
