///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CouponErrorModel {
/*
{
  "error": "sjadhd",
  "success": true
}
*/

  String? error;
  bool? success;

  CouponErrorModel({
    this.error,
    this.success,
  });
  CouponErrorModel.fromJson(Map<String, dynamic> json) {
    error = json["error"]?.toString();
    success = json["success"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["error"] = error;
    data["success"] = success;
    return data;
  }
}
