///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ErrorCheckModel {
/*
{
  "error": "sjadhd",
  "success": true
}
*/

  dynamic? success;

  ErrorCheckModel({
    this.success,
  });
  ErrorCheckModel.fromJson(Map<String, dynamic> json) {
    success = json["success"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    return data;
  }
}
