///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetVariantModelData {
/*
{
  "variation_id": 2640
}
*/

  int? variationId;

  GetVariantModelData({
    this.variationId,
  });
  GetVariantModelData.fromJson(Map<String, dynamic> json) {
    variationId = json['variation_id']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['variation_id'] = variationId;
    return data;
  }
}

class GetVariantModel {
/*
{
  "success": true,
  "data": {
    "variation_id": 2640
  }
}
*/

  bool? success;
  GetVariantModelData? data;

  GetVariantModel({
    this.success,
    this.data,
  });
  GetVariantModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = (json['data'] != null) ? GetVariantModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
