///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class NewAttributeModel {
/*
{
  "name": "Color",
  "position": 0,
  "visible": true,
  "variation": true,
  "options": [
    "Black"
  ]
}
*/

  String? name;
  int? position;
  bool? visible;
  bool? variation;
  List<String?>? options;
  String? required;

  NewAttributeModel({
    this.name,
    this.position,
    this.visible,
    this.variation,
    this.options,
    this.required
  });
  NewAttributeModel.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    position = json['position']?.toInt();
    visible = json['visible'];
    variation = json['variation'];
    if (json['options'] != null) {
      final v = json['options'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      options = arr0;
    }
    required=json['required'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['position'] = position;
    data['visible'] = visible;
    data['variation'] = variation;
    if (options != null) {
      final v = options;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['options'] = arr0;
    }
    data['required']=required;
    return data;
  }
}
