///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OrderListModelDataBillingAddress {
/*
{
  "first_name": "Keval",
  "last_name": "Panchal",
  "address": "",
  "city": "",
  "state": "",
  "postcode": "",
  "country": "",
  "email": "keval.raincreatives@gmail.com",
  "phone": "7878308210"
}
*/

  String? firstName;
  String? lastName;
  String? address;
  String? city;
  String? state;
  String? postcode;
  String? country;
  String? email;
  String? phone;

  OrderListModelDataBillingAddress({
    this.firstName,
    this.lastName,
    this.address,
    this.city,
    this.state,
    this.postcode,
    this.country,
    this.email,
    this.phone,
  });
  OrderListModelDataBillingAddress.fromJson(Map<String, dynamic> json) {
    firstName = json["first_name"]?.toString();
    lastName = json["last_name"]?.toString();
    address = json["address"]?.toString();
    city = json["city"]?.toString();
    state = json["state"]?.toString();
    postcode = json["postcode"]?.toString();
    country = json["country"]?.toString();
    email = json["email"]?.toString();
    phone = json["phone"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["first_name"] = firstName;
    data["last_name"] = lastName;
    data["address"] = address;
    data["city"] = city;
    data["state"] = state;
    data["postcode"] = postcode;
    data["country"] = country;
    data["email"] = email;
    data["phone"] = phone;
    return data;
  }
}

class OrderListModelDataShippingAddress {
/*
{
  "first_name": "Keval",
  "last_name": "Panchal",
  "address": "Hill Side",
  "city": "Valsad",
  "state": "Gujarat",
  "postcode": "396030",
  "country": "India"
}
*/

  String? firstName;
  String? lastName;
  String? address;
  String? city;
  String? state;
  String? postcode;
  String? country;

  OrderListModelDataShippingAddress({
    this.firstName,
    this.lastName,
    this.address,
    this.city,
    this.state,
    this.postcode,
    this.country,
  });
  OrderListModelDataShippingAddress.fromJson(Map<String, dynamic> json) {
    firstName = json["first_name"]?.toString();
    lastName = json["last_name"]?.toString();
    address = json["address"]?.toString();
    city = json["city"]?.toString();
    state = json["state"]?.toString();
    postcode = json["postcode"]?.toString();
    country = json["country"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["first_name"] = firstName;
    data["last_name"] = lastName;
    data["address"] = address;
    data["city"] = city;
    data["state"] = state;
    data["postcode"] = postcode;
    data["country"] = country;
    return data;
  }
}

class OrderListModelDataProducts {
/*
{
  "id": 96075,
  "variation_id": 0,
  "name": "Pack Recharge Toner HP 205A Noir Et Couleurs",
  "image": "https://encros.rcstaging.co.in/wp-content/uploads/2021/06/pack_toner_4_couleurs_1.jpg",
  "quantity": 2,
  "subtotal": "168.42106",
  "total": "168.42106"
}
*/

  int? id;
  int? variationId;
  String? name;
  String? image;
  int? quantity;
  String? subtotal;
  String? total;

  OrderListModelDataProducts({
    this.id,
    this.variationId,
    this.name,
    this.image,
    this.quantity,
    this.subtotal,
    this.total,
  });
  OrderListModelDataProducts.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    variationId = json["variation_id"]?.toInt();
    name = json["name"]?.toString();
    image = json["image"]?.toString();
    quantity = json["quantity"]?.toInt();
    subtotal = json["subtotal"]?.toString();
    total = json["total"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["variation_id"] = variationId;
    data["name"] = name;
    data["image"] = image;
    data["quantity"] = quantity;
    data["subtotal"] = subtotal;
    data["total"] = total;
    return data;
  }
}

class OrderListModelData {
/*
{
  "ID": 96121,
  "post_author": "1",
  "post_date": "2021-10-21 08:45:57",
  "post_date_gmt": "2021-10-21 08:45:57",
  "post_content": "",
  "post_title": "Order &ndash; October 21, 2021 @ 08:45 AM",
  "post_excerpt": "",
  "post_status": "wc-on-hold",
  "comment_status": "open",
  "ping_status": "closed",
  "post_password": "wc_order_3xZbkp4cpRt4u",
  "post_name": "order-oct-21-2021-0845-am",
  "to_ping": "",
  "pinged": "",
  "post_modified": "2021-10-21 08:45:57",
  "post_modified_gmt": "2021-10-21 08:45:57",
  "post_content_filtered": "",
  "post_parent": 0,
  "guid": "https://encros.rcstaging.co.in/?post_type=shop_order&#038;p=96121",
  "menu_order": 0,
  "post_type": "shop_order",
  "post_mime_type": "",
  "comment_count": "1",
  "filter": "raw",
  "cat_id": "0",
  "total": "218.42",
  "sub_total": 168.42,
  "shipping_total": "50",
  "shipping_method": "Flat rate",
  "payment_method": "Cash on delivery",
  "products": [
    {
      "id": 96075,
      "variation_id": 0,
      "name": "Pack Recharge Toner HP 205A Noir Et Couleurs",
      "image": "https://encros.rcstaging.co.in/wp-content/uploads/2021/06/pack_toner_4_couleurs_1.jpg",
      "quantity": 2,
      "subtotal": "168.42106",
      "total": "168.42106"
    }
  ],
  "shipping_address": {
    "first_name": "Keval",
    "last_name": "Panchal",
    "address": "Hill Side",
    "city": "Valsad",
    "state": "Gujarat",
    "postcode": "396030",
    "country": "India"
  },
  "billing_address": {
    "first_name": "Keval",
    "last_name": "Panchal",
    "address": "",
    "city": "",
    "state": "",
    "postcode": "",
    "country": "",
    "email": "keval.raincreatives@gmail.com",
    "phone": "7878308210"
  }
}
*/

  int? ID;
  String? postAuthor;
  String? postDate;
  String? postDateGmt;
  String? postContent;
  String? postTitle;
  String? postExcerpt;
  String? postStatus;
  String? commentStatus;
  String? pingStatus;
  String? postPassword;
  String? postName;
  String? toPing;
  String? pinged;
  String? postModified;
  String? postModifiedGmt;
  String? postContentFiltered;
  int? postParent;
  String? guid;
  int? menuOrder;
  String? postType;
  String? postMimeType;
  String? commentCount;
  String? filter;
  String? catId;
  String? total;
  double? subTotal;
  String? shippingTotal;
  String? shippingMethod;
  String? paymentMethod;
  String? order_status;
  List<OrderListModelDataProducts?>? products;
  OrderListModelDataShippingAddress? shippingAddress;
  OrderListModelDataBillingAddress? billingAddress;

  OrderListModelData({
    this.ID,
    this.postAuthor,
    this.postDate,
    this.postDateGmt,
    this.postContent,
    this.postTitle,
    this.postExcerpt,
    this.postStatus,
    this.commentStatus,
    this.pingStatus,
    this.postPassword,
    this.postName,
    this.toPing,
    this.pinged,
    this.postModified,
    this.postModifiedGmt,
    this.postContentFiltered,
    this.postParent,
    this.guid,
    this.menuOrder,
    this.postType,
    this.postMimeType,
    this.commentCount,
    this.filter,
    this.catId,
    this.total,
    this.subTotal,
    this.shippingTotal,
    this.shippingMethod,
    this.paymentMethod,
    this.order_status,
    this.products,
    this.shippingAddress,
    this.billingAddress,
  });
  OrderListModelData.fromJson(Map<String, dynamic> json) {
    ID = json["ID"]?.toInt();
    postAuthor = json["post_author"]?.toString();
    postDate = json["post_date"]?.toString();
    postDateGmt = json["post_date_gmt"]?.toString();
    postContent = json["post_content"]?.toString();
    postTitle = json["post_title"]?.toString();
    postExcerpt = json["post_excerpt"]?.toString();
    postStatus = json["post_status"]?.toString();
    commentStatus = json["comment_status"]?.toString();
    pingStatus = json["ping_status"]?.toString();
    postPassword = json["post_password"]?.toString();
    postName = json["post_name"]?.toString();
    toPing = json["to_ping"]?.toString();
    pinged = json["pinged"]?.toString();
    postModified = json["post_modified"]?.toString();
    postModifiedGmt = json["post_modified_gmt"]?.toString();
    postContentFiltered = json["post_content_filtered"]?.toString();
    postParent = json["post_parent"]?.toInt();
    guid = json["guid"]?.toString();
    menuOrder = json["menu_order"]?.toInt();
    postType = json["post_type"]?.toString();
    postMimeType = json["post_mime_type"]?.toString();
    commentCount = json["comment_count"]?.toString();
    filter = json["filter"]?.toString();
    catId = json["cat_id"]?.toString();
    total = json["total"]?.toString();
    subTotal = json["sub_total"]?.toDouble();
    shippingTotal = json["shipping_total"]?.toString();
    shippingMethod = json["shipping_method"]?.toString();
    paymentMethod = json["payment_method"]?.toString();
    order_status= json["order_status"]?.toString();
    if (json["products"] != null) {
      final v = json["products"];
      final arr0 = <OrderListModelDataProducts>[];
      v.forEach((v) {
        arr0.add(OrderListModelDataProducts.fromJson(v));
      });
      products = arr0;
    }
    shippingAddress = (json["shipping_address"] != null) ? OrderListModelDataShippingAddress.fromJson(json["shipping_address"]) : null;
    billingAddress = (json["billing_address"] != null) ? OrderListModelDataBillingAddress.fromJson(json["billing_address"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["ID"] = ID;
    data["post_author"] = postAuthor;
    data["post_date"] = postDate;
    data["post_date_gmt"] = postDateGmt;
    data["post_content"] = postContent;
    data["post_title"] = postTitle;
    data["post_excerpt"] = postExcerpt;
    data["post_status"] = postStatus;
    data["comment_status"] = commentStatus;
    data["ping_status"] = pingStatus;
    data["post_password"] = postPassword;
    data["post_name"] = postName;
    data["to_ping"] = toPing;
    data["pinged"] = pinged;
    data["post_modified"] = postModified;
    data["post_modified_gmt"] = postModifiedGmt;
    data["post_content_filtered"] = postContentFiltered;
    data["post_parent"] = postParent;
    data["guid"] = guid;
    data["menu_order"] = menuOrder;
    data["post_type"] = postType;
    data["post_mime_type"] = postMimeType;
    data["comment_count"] = commentCount;
    data["filter"] = filter;
    data["cat_id"] = catId;
    data["total"] = total;
    data["sub_total"] = subTotal;
    data["shipping_total"] = shippingTotal;
    data["shipping_method"] = shippingMethod;
    data["payment_method"] = paymentMethod;
    data["order_status"]=order_status;
    if (products != null) {
      final v = products;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["products"] = arr0;
    }
    if (shippingAddress != null) {
      data["shipping_address"] = shippingAddress!.toJson();
    }
    if (billingAddress != null) {
      data["billing_address"] = billingAddress!.toJson();
    }
    return data;
  }
}

class OrderListModel {
/*
{
  "success": true,
  "data": [
    {
      "ID": 96121,
      "post_author": "1",
      "post_date": "2021-10-21 08:45:57",
      "post_date_gmt": "2021-10-21 08:45:57",
      "post_content": "",
      "post_title": "Order &ndash; October 21, 2021 @ 08:45 AM",
      "post_excerpt": "",
      "post_status": "wc-on-hold",
      "comment_status": "open",
      "ping_status": "closed",
      "post_password": "wc_order_3xZbkp4cpRt4u",
      "post_name": "order-oct-21-2021-0845-am",
      "to_ping": "",
      "pinged": "",
      "post_modified": "2021-10-21 08:45:57",
      "post_modified_gmt": "2021-10-21 08:45:57",
      "post_content_filtered": "",
      "post_parent": 0,
      "guid": "https://encros.rcstaging.co.in/?post_type=shop_order&#038;p=96121",
      "menu_order": 0,
      "post_type": "shop_order",
      "post_mime_type": "",
      "comment_count": "1",
      "filter": "raw",
      "cat_id": "0",
      "total": "218.42",
      "sub_total": 168.42,
      "shipping_total": "50",
      "shipping_method": "Flat rate",
      "payment_method": "Cash on delivery",
      "products": [
        {
          "id": 96075,
          "variation_id": 0,
          "name": "Pack Recharge Toner HP 205A Noir Et Couleurs",
          "image": "https://encros.rcstaging.co.in/wp-content/uploads/2021/06/pack_toner_4_couleurs_1.jpg",
          "quantity": 2,
          "subtotal": "168.42106",
          "total": "168.42106"
        }
      ],
      "shipping_address": {
        "first_name": "Keval",
        "last_name": "Panchal",
        "address": "Hill Side",
        "city": "Valsad",
        "state": "Gujarat",
        "postcode": "396030",
        "country": "India"
      },
      "billing_address": {
        "first_name": "Keval",
        "last_name": "Panchal",
        "address": "",
        "city": "",
        "state": "",
        "postcode": "",
        "country": "",
        "email": "keval.raincreatives@gmail.com",
        "phone": "7878308210"
      }
    }
  ]
}
*/

  bool? success;
  List<OrderListModelData?>? data;
  String? currency;

  OrderListModel({
    this.success,
    this.data,
    this.currency
  });
  OrderListModel.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    if (json["data"] != null) {
      final v = json["data"];
      final arr0 = <OrderListModelData>[];
      v.forEach((v) {
        arr0.add(OrderListModelData.fromJson(v));
      });
      this.data = arr0;
    }
    currency= json["currency"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["data"] = arr0;
    }
    data["currency"]=currency;
    return data;
  }
}
