///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OrderWebSuccessModel {
/*
{
  "success": "true",
  "redirect_url": "https://test.ipg-online.com/connect/gateway/processing;jsessionid=EFA6946ADAB82B2C467C.dc?execution=e1s1&t=blue&r=dc&k=MTcyLjI3LjEuNDc6OTE0Mw",
  "order_id": 2833
}
*/

  String? success;
  String? redirectUrl;
  int? orderId;

  OrderWebSuccessModel({
    this.success,
    this.redirectUrl,
    this.orderId,
  });
  OrderWebSuccessModel.fromJson(Map<String, dynamic> json) {
    success = json['success']?.toString();
    redirectUrl = json['redirect_url']?.toString();
    orderId = json['order_id']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['redirect_url'] = redirectUrl;
    data['order_id'] = orderId;
    return data;
  }
}
