///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ReportProductModelResponse {
/*
{
  "success": true,
  "msg": "Mail Sent Successfully!!"
}
*/

  bool? success;
  String? msg;

  ReportProductModelResponse({
    this.success,
    this.msg,
  });
  ReportProductModelResponse.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    msg = json['msg']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['msg'] = msg;
    return data;
  }
}

class ReportProductModel {
/*
{
  "response": {
    "success": true,
    "msg": "Mail Sent Successfully!!"
  }
}
*/

  ReportProductModelResponse? response;

  ReportProductModel({
    this.response,
  });
  ReportProductModel.fromJson(Map<String, dynamic> json) {
    response = (json['response'] != null) ? ReportProductModelResponse.fromJson(json['response']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (response != null) {
      data['response'] = response!.toJson();
    }
    return data;
  }
}
