///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ReviewModelReviewsHeaders {
/*
{
  "X-WP-Total": 3,
  "X-WP-TotalPages": 1
}
*/

  int? XWPTotal;
  int? XWPTotalPages;

  ReviewModelReviewsHeaders({
    this.XWPTotal,
    this.XWPTotalPages,
  });
  ReviewModelReviewsHeaders.fromJson(Map<String, dynamic> json) {
    XWPTotal = json['X-WP-Total']?.toInt();
    XWPTotalPages = json['X-WP-TotalPages']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['X-WP-Total'] = XWPTotal;
    data['X-WP-TotalPages'] = XWPTotalPages;
    return data;
  }
}

class ReviewModelReviewsDataLinksUp {
/*
{
  "href": "https://thriftapp.rcstaging.co.in/wp-json/wc/v3/products/2879"
}
*/

  String? href;

  ReviewModelReviewsDataLinksUp({
    this.href,
  });
  ReviewModelReviewsDataLinksUp.fromJson(Map<String, dynamic> json) {
    href = json['href']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['href'] = href;
    return data;
  }
}

class ReviewModelReviewsDataLinksCollection {
/*
{
  "href": "https://thriftapp.rcstaging.co.in/wp-json/wc/v3/products/reviews"
}
*/

  String? href;

  ReviewModelReviewsDataLinksCollection({
    this.href,
  });
  ReviewModelReviewsDataLinksCollection.fromJson(Map<String, dynamic> json) {
    href = json['href']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['href'] = href;
    return data;
  }
}

class ReviewModelReviewsDataLinksSelf {
/*
{
  "href": "https://thriftapp.rcstaging.co.in/wp-json/wc/v3/products/reviews/71"
}
*/

  String? href;

  ReviewModelReviewsDataLinksSelf({
    this.href,
  });
  ReviewModelReviewsDataLinksSelf.fromJson(Map<String, dynamic> json) {
    href = json['href']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['href'] = href;
    return data;
  }
}

class ReviewModelReviewsDataLinks {
/*
{
  "self": [
    {
      "href": "https://thriftapp.rcstaging.co.in/wp-json/wc/v3/products/reviews/71"
    }
  ],
  "collection": [
    {
      "href": "https://thriftapp.rcstaging.co.in/wp-json/wc/v3/products/reviews"
    }
  ],
  "up": [
    {
      "href": "https://thriftapp.rcstaging.co.in/wp-json/wc/v3/products/2879"
    }
  ]
}
*/

  List<ReviewModelReviewsDataLinksSelf?>? self;
  List<ReviewModelReviewsDataLinksCollection?>? collection;
  List<ReviewModelReviewsDataLinksUp?>? up;

  ReviewModelReviewsDataLinks({
    this.self,
    this.collection,
    this.up,
  });
  ReviewModelReviewsDataLinks.fromJson(Map<String, dynamic> json) {
    if (json['self'] != null) {
      final v = json['self'];
      final arr0 = <ReviewModelReviewsDataLinksSelf>[];
      v.forEach((v) {
        arr0.add(ReviewModelReviewsDataLinksSelf.fromJson(v));
      });
      self = arr0;
    }
    if (json['collection'] != null) {
      final v = json['collection'];
      final arr0 = <ReviewModelReviewsDataLinksCollection>[];
      v.forEach((v) {
        arr0.add(ReviewModelReviewsDataLinksCollection.fromJson(v));
      });
      collection = arr0;
    }
    if (json['up'] != null) {
      final v = json['up'];
      final arr0 = <ReviewModelReviewsDataLinksUp>[];
      v.forEach((v) {
        arr0.add(ReviewModelReviewsDataLinksUp.fromJson(v));
      });
      up = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (self != null) {
      final v = self;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['self'] = arr0;
    }
    if (collection != null) {
      final v = collection;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['collection'] = arr0;
    }
    if (up != null) {
      final v = up;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['up'] = arr0;
    }
    return data;
  }
}

class ReviewModelReviewsDataReviewerAvatarUrls {
/*
{
  "24": "https://secure.gravatar.com/avatar/093fb4dd97a62bfba128639e6ed46023?s=24&d=mm&r=g",
  "48": "https://secure.gravatar.com/avatar/093fb4dd97a62bfba128639e6ed46023?s=48&d=mm&r=g",
  "96": "https://secure.gravatar.com/avatar/093fb4dd97a62bfba128639e6ed46023?s=96&d=mm&r=g"
}
*/

  String? the24;
  String? the48;
  String? the96;

  ReviewModelReviewsDataReviewerAvatarUrls({
    this.the24,
    this.the48,
    this.the96,
  });
  ReviewModelReviewsDataReviewerAvatarUrls.fromJson(Map<String, dynamic> json) {
    the24 = json['24']?.toString();
    the48 = json['48']?.toString();
    the96 = json['96']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['24'] = the24;
    data['48'] = the48;
    data['96'] = the96;
    return data;
  }
}

class ReviewModelReviewsData {
/*
{
  "id": 71,
  "date_created": "2022-02-23T10:01:22",
  "date_created_gmt": "2022-02-23T10:01:22",
  "product_id": 2879,
  "status": "approved",
  "reviewer": "mayank@gmail.com",
  "reviewer_email": "mayank@gmail.com",
  "review": "<p>bad quality</p>\n",
  "rating": 2,
  "verified": false,
  "reviewer_avatar_urls": {
    "24": "https://secure.gravatar.com/avatar/093fb4dd97a62bfba128639e6ed46023?s=24&d=mm&r=g",
    "48": "https://secure.gravatar.com/avatar/093fb4dd97a62bfba128639e6ed46023?s=48&d=mm&r=g",
    "96": "https://secure.gravatar.com/avatar/093fb4dd97a62bfba128639e6ed46023?s=96&d=mm&r=g"
  },
  "_links": {
    "self": [
      {
        "href": "https://thriftapp.rcstaging.co.in/wp-json/wc/v3/products/reviews/71"
      }
    ],
    "collection": [
      {
        "href": "https://thriftapp.rcstaging.co.in/wp-json/wc/v3/products/reviews"
      }
    ],
    "up": [
      {
        "href": "https://thriftapp.rcstaging.co.in/wp-json/wc/v3/products/2879"
      }
    ]
  }
}
*/

  int? id;
  String? dateCreated;
  String? dateCreatedGmt;
  int? productId;
  String? status;
  String? reviewer;
  String? reviewerEmail;
  String? review;
  int? rating;
  bool? verified;

  ReviewModelReviewsData({
    this.id,
    this.dateCreated,
    this.dateCreatedGmt,
    this.productId,
    this.status,
    this.reviewer,
    this.reviewerEmail,
    this.review,
    this.rating,
    this.verified,
  });
  ReviewModelReviewsData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    dateCreated = json['date_created']?.toString();
    dateCreatedGmt = json['date_created_gmt']?.toString();
    productId = json['product_id']?.toInt();
    status = json['status']?.toString();
    reviewer = json['reviewer']?.toString();
    reviewerEmail = json['reviewer_email']?.toString();
    review = json['review']?.toString();
    rating = json['rating']?.toInt();
    verified = json['verified'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['date_created'] = dateCreated;
    data['date_created_gmt'] = dateCreatedGmt;
    data['product_id'] = productId;
    data['status'] = status;
    data['reviewer'] = reviewer;
    data['reviewer_email'] = reviewerEmail;
    data['review'] = review;
    data['rating'] = rating;
    data['verified'] = verified;
    return data;
  }
}

class ReviewModelReviews {
/*
{
  "data": [
    {
      "id": 71,
      "date_created": "2022-02-23T10:01:22",
      "date_created_gmt": "2022-02-23T10:01:22",
      "product_id": 2879,
      "status": "approved",
      "reviewer": "mayank@gmail.com",
      "reviewer_email": "mayank@gmail.com",
      "review": "<p>bad quality</p>\n",
      "rating": 2,
      "verified": false,
      "reviewer_avatar_urls": {
        "24": "https://secure.gravatar.com/avatar/093fb4dd97a62bfba128639e6ed46023?s=24&d=mm&r=g",
        "48": "https://secure.gravatar.com/avatar/093fb4dd97a62bfba128639e6ed46023?s=48&d=mm&r=g",
        "96": "https://secure.gravatar.com/avatar/093fb4dd97a62bfba128639e6ed46023?s=96&d=mm&r=g"
      },
      "_links": {
        "self": [
          {
            "href": "https://thriftapp.rcstaging.co.in/wp-json/wc/v3/products/reviews/71"
          }
        ],
        "collection": [
          {
            "href": "https://thriftapp.rcstaging.co.in/wp-json/wc/v3/products/reviews"
          }
        ],
        "up": [
          {
            "href": "https://thriftapp.rcstaging.co.in/wp-json/wc/v3/products/2879"
          }
        ]
      }
    }
  ],
  "headers": {
    "X-WP-Total": 3,
    "X-WP-TotalPages": 1
  },
  "status": 200
}
*/

  List<ReviewModelReviewsData?>? data;

  ReviewModelReviews({
    this.data
  });
  ReviewModelReviews.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <ReviewModelReviewsData>[];
      v.forEach((v) {
        arr0.add(ReviewModelReviewsData.fromJson(v));
      });
      this.data = arr0;
    }

  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}

class ReviewModel {
/*
{
  "success": true,
  "reviews": {
    "data": [
      {
        "id": 71,
        "date_created": "2022-02-23T10:01:22",
        "date_created_gmt": "2022-02-23T10:01:22",
        "product_id": 2879,
        "status": "approved",
        "reviewer": "mayank@gmail.com",
        "reviewer_email": "mayank@gmail.com",
        "review": "<p>bad quality</p>\n",
        "rating": 2,
        "verified": false,
        "reviewer_avatar_urls": {
          "24": "https://secure.gravatar.com/avatar/093fb4dd97a62bfba128639e6ed46023?s=24&d=mm&r=g",
          "48": "https://secure.gravatar.com/avatar/093fb4dd97a62bfba128639e6ed46023?s=48&d=mm&r=g",
          "96": "https://secure.gravatar.com/avatar/093fb4dd97a62bfba128639e6ed46023?s=96&d=mm&r=g"
        },
        "_links": {
          "self": [
            {
              "href": "https://thriftapp.rcstaging.co.in/wp-json/wc/v3/products/reviews/71"
            }
          ],
          "collection": [
            {
              "href": "https://thriftapp.rcstaging.co.in/wp-json/wc/v3/products/reviews"
            }
          ],
          "up": [
            {
              "href": "https://thriftapp.rcstaging.co.in/wp-json/wc/v3/products/2879"
            }
          ]
        }
      }
    ],
    "headers": {
      "X-WP-Total": 3,
      "X-WP-TotalPages": 1
    },
    "status": 200
  }
}
*/

  bool? success;
  dynamic? average;
  ReviewModelReviews? reviews;

  ReviewModel({
    this.success,
    this.average,
    this.reviews,
  });
  ReviewModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    average= json['average'];
    reviews = (json['reviews'] != null) ? ReviewModelReviews.fromJson(json['reviews']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['average']=average;
    if (reviews != null) {
      data['reviews'] = reviews!.toJson();
    }
    return data;
  }
}
