///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ShipmentModelLinksCollection {
/*
{
  "href": "https://encros.rcstaging.co.in/wp-json/wc/v3/shipping_methods"
}
*/

  String? href;

  ShipmentModelLinksCollection({
    this.href,
  });
  ShipmentModelLinksCollection.fromJson(Map<String, dynamic> json) {
    href = json["href"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["href"] = href;
    return data;
  }
}

class ShipmentModelLinksSelf {
/*
{
  "href": "https://encros.rcstaging.co.in/wp-json/wc/v3/shipping_methods/flat_rate"
}
*/

  String? href;

  ShipmentModelLinksSelf({
    this.href,
  });
  ShipmentModelLinksSelf.fromJson(Map<String, dynamic> json) {
    href = json["href"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["href"] = href;
    return data;
  }
}

class ShipmentModelLinks {
/*
{
  "self": [
    {
      "href": "https://encros.rcstaging.co.in/wp-json/wc/v3/shipping_methods/flat_rate"
    }
  ],
  "collection": [
    {
      "href": "https://encros.rcstaging.co.in/wp-json/wc/v3/shipping_methods"
    }
  ]
}
*/

  List<ShipmentModelLinksSelf?>? self;
  List<ShipmentModelLinksCollection?>? collection;

  ShipmentModelLinks({
    this.self,
    this.collection,
  });
  ShipmentModelLinks.fromJson(Map<String, dynamic> json) {
    if (json["self"] != null) {
      final v = json["self"];
      final arr0 = <ShipmentModelLinksSelf>[];
      v.forEach((v) {
        arr0.add(ShipmentModelLinksSelf.fromJson(v));
      });
      self = arr0;
    }
    if (json["collection"] != null) {
      final v = json["collection"];
      final arr0 = <ShipmentModelLinksCollection>[];
      v.forEach((v) {
        arr0.add(ShipmentModelLinksCollection.fromJson(v));
      });
      collection = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (self != null) {
      final v = self;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["self"] = arr0;
    }
    if (collection != null) {
      final v = collection;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["collection"] = arr0;
    }
    return data;
  }
}

class ShipmentModel {
/*
{
  "id": "flat_rate",
  "title": "Flat rate",
  "description": "Lets you charge a fixed rate for shipping.",
  "_links": {
    "self": [
      {
        "href": "https://encros.rcstaging.co.in/wp-json/wc/v3/shipping_methods/flat_rate"
      }
    ],
    "collection": [
      {
        "href": "https://encros.rcstaging.co.in/wp-json/wc/v3/shipping_methods"
      }
    ]
  }
}
*/

  String? id;
  String? title;
  String? description;
  ShipmentModelLinks? Links;

  ShipmentModel({
    this.id,
    this.title,
    this.description,
    this.Links,
  });
  ShipmentModel.fromJson(Map<dynamic, dynamic> json) {
    id = json["id"]?.toString();
    title = json["title"]?.toString();
    description = json["description"]?.toString();
    Links = (json["_links"] != null) ? ShipmentModelLinks.fromJson(json["_links"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["title"] = title;
    data["description"] = description;
    if (Links != null) {
      data["_links"] = Links!.toJson();
    }
    return data;
  }
}
