///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ShLoginModelAllcaps {
/*
{
  "read": true,
  "level_0": true,
  "subscriber": true
}
*/

  bool? read;
  bool? level_0;
  bool? subscriber;

  ShLoginModelAllcaps({
    this.read,
    this.level_0,
    this.subscriber,
  });
  ShLoginModelAllcaps.fromJson(Map<String, dynamic> json) {
    read = json["read"];
    level_0 = json["level_0"];
    subscriber = json["subscriber"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["read"] = read;
    data["level_0"] = level_0;
    data["subscriber"] = subscriber;
    return data;
  }
}

class ShLoginModelCaps {
/*
{
  "subscriber": true
}
*/

  bool? subscriber;

  ShLoginModelCaps({
    this.subscriber,
  });
  ShLoginModelCaps.fromJson(Map<String, dynamic> json) {
    subscriber = json["subscriber"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["subscriber"] = subscriber;
    return data;
  }
}

class ShLoginModelData {
/*
{
  "ID": "16123",
  "user_login": "keval.raincreatives@gmail.com",
  "user_pass": "$P$BSK1BiYBFJtidEg7ce6buCZ4..D6W61",
  "user_nicename": "keval-raincreativesgmail-com",
  "user_email": "keval.raincreatives@gmail.com",
  "user_url": "",
  "user_registered": "2021-10-04 09:31:58",
  "user_activation_key": "",
  "user_status": "0",
  "display_name": "keval.raincreatives@gmail.com",
  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvZW5jcm9zLnJjc3RhZ2luZy5jby5pbiIsImlhdCI6MTYzNDEwMjc2NywibmJmIjoxNjM0MTAyNzY3LCJleHAiOjE2MzQ3MDc1NjcsImRhdGEiOnsidXNlciI6eyJpZCI6IjE2MTIzIn19fQ.E0OxZo_54PPOMvvP2jJLthGHcuwr4VYlBW3_IZepwHQ"
}
*/

  String? ID;
  String? userLogin;
  String? userPass;
  String? userNicename;
  String? userEmail;
  String? userUrl;
  String? userRegistered;
  String? userActivationKey;
  String? userStatus;
  String? displayName;
  String? token;
  int? is_store_owner;
  String? country;
  String? verified;

  ShLoginModelData({
    this.ID,
    this.userLogin,
    this.userPass,
    this.userNicename,
    this.userEmail,
    this.userUrl,
    this.userRegistered,
    this.userActivationKey,
    this.userStatus,
    this.displayName,
    this.token,
    this.is_store_owner,
    this.country,
    this.verified
  });
  ShLoginModelData.fromJson(Map<String, dynamic> json) {
    ID = json["ID"]?.toString();
    userLogin = json["user_login"]?.toString();
    userPass = json["user_pass"]?.toString();
    userNicename = json["user_nicename"]?.toString();
    userEmail = json["user_email"]?.toString();
    userUrl = json["user_url"]?.toString();
    userRegistered = json["user_registered"]?.toString();
    userActivationKey = json["user_activation_key"]?.toString();
    userStatus = json["user_status"]?.toString();
    displayName = json["display_name"]?.toString();
    token = json["token"]?.toString();
    is_store_owner= json["is_store_owner"];
    country= json["country"];
    verified= json["verified"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["ID"] = ID;
    data["user_login"] = userLogin;
    data["user_pass"] = userPass;
    data["user_nicename"] = userNicename;
    data["user_email"] = userEmail;
    data["user_url"] = userUrl;
    data["user_registered"] = userRegistered;
    data["user_activation_key"] = userActivationKey;
    data["user_status"] = userStatus;
    data["display_name"] = displayName;
    data["token"] = token;
    data["is_store_owner"]=is_store_owner;
    data["country"]=country;
    data["verified"]=verified;
    return data;
  }
}

class ShLoginModel {
/*
{
  "data": {
    "ID": "16123",
    "user_login": "keval.raincreatives@gmail.com",
    "user_pass": "$P$BSK1BiYBFJtidEg7ce6buCZ4..D6W61",
    "user_nicename": "keval-raincreativesgmail-com",
    "user_email": "keval.raincreatives@gmail.com",
    "user_url": "",
    "user_registered": "2021-10-04 09:31:58",
    "user_activation_key": "",
    "user_status": "0",
    "display_name": "keval.raincreatives@gmail.com",
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvZW5jcm9zLnJjc3RhZ2luZy5jby5pbiIsImlhdCI6MTYzNDEwMjc2NywibmJmIjoxNjM0MTAyNzY3LCJleHAiOjE2MzQ3MDc1NjcsImRhdGEiOnsidXNlciI6eyJpZCI6IjE2MTIzIn19fQ.E0OxZo_54PPOMvvP2jJLthGHcuwr4VYlBW3_IZepwHQ"
  },
  "ID": 16123,
  "caps": {
    "subscriber": true
  },
  "cap_key": "encros_capabilities",
  "roles": [
    "subscriber"
  ],
  "allcaps": {
    "read": true,
    "level_0": true,
    "subscriber": true
  },
  "filter": null
}
*/

  ShLoginModelData? data;
  int? ID;
  ShLoginModelCaps? caps;
  String? capKey;
  List<String?>? roles;
  ShLoginModelAllcaps? allcaps;
  String? filter;

  ShLoginModel({
    this.data,
    this.ID,
    this.caps,
    this.capKey,
    this.roles,
    this.allcaps,
    this.filter,
  });
  ShLoginModel.fromJson(Map<String, dynamic> json) {
    data = (json["data"] != null) ? ShLoginModelData.fromJson(json["data"]) : null;
    ID = json["ID"]?.toInt();
    caps = (json["caps"] != null) ? ShLoginModelCaps.fromJson(json["caps"]) : null;
    capKey = json["cap_key"]?.toString();
    if (json["roles"] != null) {
      final v = json["roles"];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      roles = arr0;
    }
    allcaps = (json["allcaps"] != null) ? ShLoginModelAllcaps.fromJson(json["allcaps"]) : null;
    filter = json["filter"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["ID"] = ID;
    if (caps != null) {
      data["caps"] = caps!.toJson();
    }
    data["cap_key"] = capKey;
    if (roles != null) {
      final v = roles;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data["roles"] = arr0;
    }
    if (allcaps != null) {
      data["allcaps"] = allcaps!.toJson();
    }
    data["filter"] = filter;
    return data;
  }
}
