///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TermsModelData {
/*
{
  "content": "<p>Terms and Conditions content</p>\n"
}
*/

  String? content;

  TermsModelData({
    this.content,
  });
  TermsModelData.fromJson(Map<String, dynamic> json) {
    content = json['content']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['content'] = content;
    return data;
  }
}

class TermsModel {
/*
{
  "success": true,
  "data": {
    "content": "<p>Terms and Conditions content</p>\n"
  }
}
*/

  bool? success;
  TermsModelData? data;

  TermsModel({
    this.success,
    this.data,
  });
  TermsModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = (json['data'] != null) ? TermsModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
