///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserDelModel {
/*
{
  "success": true
}
*/

  bool? success;

  UserDelModel({
    this.success,
  });
  UserDelModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    return data;
  }
}
