///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ViewProModel {
/*
{
  "profile_picture": "https://thriftapp.rcstaging.co.in/wp-content/uploads/2022/08/1657633408_scaled_image_picker4449041638212571650-1.jpg",
  "name_of_account": "dsdd",
  "account_number": "sdfsf",
  "name_of_bank": "sdfdsf",
  "other_details": "dsfdsf"
} 
*/

  String? profilePicture;
  String? nameOfAccount;
  String? accountNumber;
  String? nameOfBank;
  String? otherDetails;

  ViewProModel({
    this.profilePicture,
    this.nameOfAccount,
    this.accountNumber,
    this.nameOfBank,
    this.otherDetails,
  });
  ViewProModel.fromJson(Map<String, dynamic> json) {
    profilePicture = json['profile_picture']?.toString();
    nameOfAccount = json['name_of_account']?.toString();
    accountNumber = json['account_number']?.toString();
    nameOfBank = json['name_of_bank']?.toString();
    otherDetails = json['other_details']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['profile_picture'] = profilePicture;
    data['name_of_account'] = nameOfAccount;
    data['account_number'] = accountNumber;
    data['name_of_bank'] = nameOfBank;
    data['other_details'] = otherDetails;
    return data;
  }
}
