///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OfferModelLinksCollection {
/*
{
  "href": "https://encros.rcstaging.co.in/wp-json/wc/v3/coupons"
}
*/

  String? href;

  OfferModelLinksCollection({
    this.href,
  });
  OfferModelLinksCollection.fromJson(Map<String, dynamic> json) {
    href = json['href']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['href'] = href;
    return data;
  }
}

class OfferModelLinksSelf {
/*
{
  "href": "https://encros.rcstaging.co.in/wp-json/wc/v3/coupons/96153"
}
*/

  String? href;

  OfferModelLinksSelf({
    this.href,
  });
  OfferModelLinksSelf.fromJson(Map<String, dynamic> json) {
    href = json['href']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['href'] = href;
    return data;
  }
}

class OfferModelLinks {
/*
{
  "self": [
    {
      "href": "https://encros.rcstaging.co.in/wp-json/wc/v3/coupons/96153"
    }
  ],
  "collection": [
    {
      "href": "https://encros.rcstaging.co.in/wp-json/wc/v3/coupons"
    }
  ]
}
*/

  List<OfferModelLinksSelf?>? self;
  List<OfferModelLinksCollection?>? collection;

  OfferModelLinks({
    this.self,
    this.collection,
  });
  OfferModelLinks.fromJson(Map<String, dynamic> json) {
    if (json['self'] != null) {
      final v = json['self'];
      final arr0 = <OfferModelLinksSelf>[];
      v.forEach((v) {
        arr0.add(OfferModelLinksSelf.fromJson(v));
      });
      self = arr0;
    }
    if (json['collection'] != null) {
      final v = json['collection'];
      final arr0 = <OfferModelLinksCollection>[];
      v.forEach((v) {
        arr0.add(OfferModelLinksCollection.fromJson(v));
      });
      collection = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (self != null) {
      final v = self;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['self'] = arr0;
    }
    if (collection != null) {
      final v = collection;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['collection'] = arr0;
    }
    return data;
  }
}

class OfferModel {
/*
{
  "id": 96153,
  "code": "flat100",
  "amount": "100.00",
  "date_created": "2021-11-01T11:07:18",
  "date_created_gmt": "2021-11-01T11:07:18",
  "date_modified": "2021-11-01T11:07:18",
  "date_modified_gmt": "2021-11-01T11:07:18",
  "discount_type": "fixed_cart",
  "description": "Flat 100 Amount Discount On Order Total",
  "date_expires": null,
  "date_expires_gmt": null,
  "usage_count": 0,
  "individual_use": false,
  "product_ids": [
    null
  ],
  "excluded_product_ids": [
    null
  ],
  "usage_limit": null,
  "usage_limit_per_user": null,
  "limit_usage_to_x_items": null,
  "free_shipping": false,
  "product_categories": [
    null
  ],
  "excluded_product_categories": [
    null
  ],
  "exclude_sale_items": false,
  "minimum_amount": "0.00",
  "maximum_amount": "0.00",
  "email_restrictions": [
    null
  ],
  "used_by": [
    null
  ],
  "meta_data": [
    null
  ],
  "_links": {
    "self": [
      {
        "href": "https://encros.rcstaging.co.in/wp-json/wc/v3/coupons/96153"
      }
    ],
    "collection": [
      {
        "href": "https://encros.rcstaging.co.in/wp-json/wc/v3/coupons"
      }
    ]
  }
}
*/

  int? id;
  String? code;
  String? amount;
  String? dateCreated;
  String? dateCreatedGmt;
  String? dateModified;
  String? dateModifiedGmt;
  String? discountType;
  String? description;
  String? dateExpires;
  String? dateExpiresGmt;
  int? usageCount;
  bool? individualUse;

  String? usageLimit;
  String? usageLimitPerUser;
  String? limitUsageToXItems;
  bool? freeShipping;
  bool? excludeSaleItems;
  String? minimumAmount;
  String? maximumAmount;

  OfferModel({
    this.id,
    this.code,
    this.amount,
    this.dateCreated,
    this.dateCreatedGmt,
    this.dateModified,
    this.dateModifiedGmt,
    this.discountType,
    this.description,
    this.dateExpires,
    this.dateExpiresGmt,
    this.usageCount,
    this.individualUse,
    this.usageLimit,
    this.usageLimitPerUser,
    this.limitUsageToXItems,
    this.freeShipping,
    this.excludeSaleItems,
    this.minimumAmount,
    this.maximumAmount,
  });
  OfferModel.fromJson(Map<dynamic, dynamic> json) {
    id = json['id']?.toInt();
    code = json['code']?.toString();
    amount = json['amount']?.toString();
    dateCreated = json['date_created']?.toString();
    dateCreatedGmt = json['date_created_gmt']?.toString();
    dateModified = json['date_modified']?.toString();
    dateModifiedGmt = json['date_modified_gmt']?.toString();
    discountType = json['discount_type']?.toString();
    description = json['description']?.toString();
    dateExpires = json['date_expires']?.toString();
    dateExpiresGmt = json['date_expires_gmt']?.toString();
    usageCount = json['usage_count']?.toInt();
    individualUse = json['individual_use'];
    usageLimitPerUser = json['usage_limit_per_user']?.toString();
    limitUsageToXItems = json['limit_usage_to_x_items']?.toString();
    freeShipping = json['free_shipping'];
    minimumAmount = json['minimum_amount']?.toString();
    maximumAmount = json['maximum_amount']?.toString();
    }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['code'] = code;
    data['amount'] = amount;
    data['date_created'] = dateCreated;
    data['date_created_gmt'] = dateCreatedGmt;
    data['date_modified'] = dateModified;
    data['date_modified_gmt'] = dateModifiedGmt;
    data['discount_type'] = discountType;
    data['description'] = description;
    data['date_expires'] = dateExpires;
    data['date_expires_gmt'] = dateExpiresGmt;
    data['usage_count'] = usageCount;
    data['individual_use'] = individualUse;
    data['usage_limit_per_user'] = usageLimitPerUser;
    data['limit_usage_to_x_items'] = limitUsageToXItems;
    data['free_shipping'] = freeShipping;
    data['minimum_amount'] = minimumAmount;
    data['maximum_amount'] = maximumAmount;
    return data;
  }
}
